### PR TITLE
Compatibility update

### PR DESCRIPTION
**Pull request by compwright**
* Fix compatibility with mongoose-document-versioner and Mongoose 5.2
    ```
    MongoError: unknown top level operator: $inc
    ```
* Update dependencies and fix security vulnerabilities

### CODE REVIEW

**Comment by codepunkt** [comment]
hey @compwright, thanks for the PR! 😁

What is the problem that this PR tries to fix? Please be as detailed as possible so i can decide whether to merge or not.

**Comment by compwright** [comment]
@codepunkt the description seems to cover the bases, essentially I couldn't use this as-is because of outdated dependencies triggering security warnings, and because of the error cited in the description which happens when you try to use this plugin with Mongoose 5.2 with the `$inc` operator in a query.

**Comment by codepunkt** [comment]
Is this a problem that is specific to mongoose-versioner or do we have a general problem with $inc on updates? Also, do you work with a fork now that this hasn't been merged in a while?

**Comment by bausmeier** [comment]
We're experiencing the same issue with the `$push` and `$pull` operations.

**Comment by codepunkt** [comment]
@compwright @mbaertschi @bausmeier  I'm not actively using this plugin (or mongoose) at the moment. I would merge if someone could explain what the problem is (mongoose 5.2 and $inc updates, but what exactly and how does that relate to mongoose-document-versioner) and how this PR fixes it.

**Comment by compwright** [comment]
@codepunkt it's been a while since I touched this so going off memory here, but this implementation manipulates internal properties of the Mongoose query, which are version specific and subject to change as Mongoose develops.

The current implementation of this plugin doesn't check for all possible MongoDB special operators when it calculates the before/after document state so that it can run a diff.

Right now `$set` is the only special query operator that this plugin checks for, when in fact there may be others present, such as `$inc`, `$push`, or `$pull`. This PR accounts for all current and future special operators that begin with `$`.

**Comment by bausmeier** [comment]
@codepunkt I'm not familiar with mongoose-document-versioner, but we have been experiencing a similar issue when upgrading Mongoose with the use of $push and $pull in our updateMany queries. The implementation in this PR does not cater for all cases, e.g. when using $pull to remove a value which is also part of the filter condition, so I opened another PR (https://github.com/codepunkt/mongoose-patch-history/pull/30) which takes a different approach, but solves the same problem. I also added a short explanation of the problem in the description of that PR, but if it's not clear I'm happy to explain further.

**Pull request closed without merging**
