### PR TITLE
Draft: Bug update one not returning

### PR DESCRIPTION
**Pull request by vinerich**
This PRs purpose is to do advanced matrix testing on timeout bugs. (#71)

### CODE REVIEW

**Comment by vinerich** [comment]
@codepunkt if you look at the above test output you can see that a timeout issue is happening with the newest mongoose version.

To which version you would like to be compatible? We are currently working with `5.6.x` and `5.10.x` is the newest minor.

**Comment by codepunkt** [comment]
@vinerich As i'm not using this at the moment, it doesn't really matter to me personally. You're doing a great job maintaing at the moment, so i already thought about giving you at least GitHub contribution rights as a first step.

However, thinking about this just from a users perspective, i'd of course always want to support the latest mongoose versions.

**Comment by vinerich** [comment]
@codepunkt This would be my first project then. At the moment I got the time for this and am using it actively so I'd be good with it.
However sometimes I'll probably mention you 😄 

I need to specify the question: Support only the latest or implement a fix to support back to 5.x?
I can check on that while working out the details. Maybe it is trivial to support older versions.

They don't. I'll report back when I know the cause.

**Comment by vinerich** [comment]
Closing in favor of #73.

**Pull request closed without merging**
