### PR TITLE
Dependencies update

### PR DESCRIPTION
**Pull request by mbaertschi**
This PR also includes PR #15  and PR #16

### CODE REVIEW

**Comment by codepunkt** [comment]
@mbaertschi Thank you for your efforts and sorry for the delay on my end! What seems to be missing is the documentation of the `trackOriginalValue` option in `README.md`.

I'm happy to merge once that option is documented! 👍

**Comment by mbaertschi** [comment]
@codepunkt I added a short information about `trackOriginalValue` in `README.md` and updated mongoose to `v5.0.13` as well.

**Comment by codepunkt** [comment]
@mbaertschi Thanks!

**Comment by codepunkt** [comment]
Released as `1.3.0`

**Pull request merged**
