### PR TITLE
Support Mongoose .update and .findOneAndUpdate

### LINKED ISSUE #11: Mongoose .update and .findByIdAndUpdate seems to not trigger 'patching'
Hello,

As the title say, i can only get the plugin to work when i, like the doc,  do a ` Model.find()` ,  then, on the found document, do a `.set().save()` .
I'm a begginner so i might be wrong, but is this a Mongoose limitations? I found this bit in the Mongoose doc: 

> Although values are casted to their appropriate types when using update, the following are not applied:
> 
> defaults
> setters
> validators
> middleware
> If you need those features, use the traditional approach of first retrieving the document.

Is this the reason?

### PR DESCRIPTION
**Pull request by compwright**
* Added support for `findByIdAndUpdate`, `findOneAndUpdate`, `updateOne`, `updateMany`, and `update` queries
* Fix `jsonpatch.apply` deprecation warning
* Fixed `mongoose.connect` deprecation warning

Resolves #11

### CODE REVIEW

**Comment by codepunkt** [comment]
@compwright Thanks, that looks really good!

I'm not sure when i'll be able to have a deeper look into this. Also, there is a problem with travis CI at the moment, which unfortunately doesn't run tests including mongodb on pull requests.

Do you use your version in production somewhere? Is it backwards compatible to the previous one?

**Comment by codepunkt** [comment]
@compwright I've updated the CI configuration on master. Please update your pull request to include those changes!

**Comment by compwright** [comment]
@codepunkt I've rebased and tests are passing. There should be no backward-compatibility issues, but I would recommend releasing this as a minor version update (not a patch) since this represents added features. I am using it in production.

**Comment by codepunkt** [comment]
@compwright Thanks! Published as `v1.2.0`!

**Comment by compwright** [comment]
Thanks Chris! I really appreciate it.

**Comment by codepunkt** [comment]
You're welcome. Thanks for your engagement! 👍

**Pull request merged**
