### PR TITLE
Fix null pointer exception for postUpdateOne

### PR DESCRIPTION
**Pull request by bloodhawk**

### CODE REVIEW

**Comment by codepunkt** [comment]
hey @bloodhawk, thanks for the PR! 😁 

What is the problem that this PR tries to fix? Please be as detailed as possible so i can decide whether to merge or not.

**Comment by bloodhawk** [comment]
Hey @codepunkt this fixes: https://github.com/codepunkt/mongoose-patch-history/issues/22

**Comment by codepunkt** [comment]
The whole test changes are just formatting, right?

**Comment by bloodhawk** [comment]
Correct @codepunkt

**Pull request merged**
